### ISSUE TITLE
Deprecation warning in Ansible 2.8 (for 2.12): `Invoking "yum" only once while using a loop via squash_actions is deprecated`

### ISSUE THREAD

**Issue by markvdlaan93** [suzuki-shunsuke/ansible-pyenv#18]
I'm currently getting deprecation warnings for this module in Ansible 2.8:

_[DEPRECATION WARNING]: Invoking "yum" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: "{{ query('flattened', 
['{{ pyenv_redhat_build_dependencies }}', '{{ 
pyenv_redhat_additional_build_dependencies }}']) }}"` and remove the loop. This
 feature will be removed in version 2.11. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg._

The problem is probably in: https://github.com/suzuki-shunsuke/ansible-pyenv/blob/master/tasks/RedHat.yml#L5

Can this be fixed?

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/ansible-pyenv/pull/20

**Comment by suzuki-shunsuke** [comment]
I have released the new version v4.0.0.
Please check it.

**Comment by markvdlaan93** [comment]
Deprecation warnings are fixed :-). Thanks for the quick response and fix

**Comment by suzuki-shunsuke** [comment]
Thank you for your checking.
I close this issue.
