### ISSUE TITLE
Deprecation warning in Ansible 2.8 (for 2.12): `The use of 'static' has been deprecated. Use  'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.`

### ISSUE THREAD

**Issue by markvdlaan93** [suzuki-shunsuke/ansible-pyenv#19]
I'm getting a deprecation warning in Ansible 2.8:

_[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg._

The problem is probably in: https://github.com/suzuki-shunsuke/ansible-pyenv/blob/f9aea6489d7921bbcd417713c790ade72fbfa751/tasks/main.yml#L32

Can this be fixed?

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!
I'll check.

**Comment by suzuki-shunsuke** [comment]
I have released the new version v4.0.0.
Please check it.
